language: generic
sudo: required

services:
  - docker

before_install:
  # Specify a dockerfile and say to get a client dir as a context
  - docker build -t alexchromets/react-test -f ./client/Dockerfile.dev ./client

# -e CI=true (for exit after tests execution)
script:
  - docker run -e CI=true alexchromets/react-test npm run test -- --coverage

after_success:
  - docker build -t alexchromets/multi-client ./client
  - docker build -t alexchromets/multi-nginx ./nginx
  - docker build -t alexchromets/multi-server ./server
  - docker build -t alexchromets/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push built images to docker hub
  - docker push alexchromets/multi-client
  - docker push alexchromets/multi-nginx
  - docker push alexchromets/multi-server
  - docker push alexchromets/multi-worker
